# Generated by Django 3.0.3 on 2020-08-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', null=True, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(null=True, related_name='film_director', to='movies.Director', verbose_name='режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_russia',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', null=True, verbose_name='Сборы в России'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', null=True, verbose_name='Сборы в США'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fees_in_world',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', null=True, verbose_name='Сборы в мире'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film_class',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(null=True, to='movies.Genre', verbose_name='жанры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, null=True, verbose_name='Дата выхода'),
        ),
    ]
