# Generated by Django 3.0.3 on 2020-08-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200819_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='film_director', to='movies.Director', verbose_name='режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='жанры'),
        ),
    ]
