# Generated by Django 3.0.3 on 2020-08-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200819_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.TextField(default=10, max_length=5, null=True, verbose_name='Рейтинг на Кинопоиске'),
        ),
    ]
